### PR TITLE
Functionality to add custom enemies into the lethal company built in dev mode menu.

### PR DESCRIPTION
**Pull request by VisualError**
What changed:
* `NetworkPrefabs.cs` - I took the network prefab code from the dev branch because of possibly outdated code from the main branch.
* `Enemies.cs` - Added a hook to `QuickMenuManager_Start`, which is what adds in enemies to the dev mode menu.

The way I'm checking if `addedToDebug` is `true` can be changed to a different method of checking whether the enemies have been added to the menu.

### CODE REVIEW

**Comment by EvaisaDev** [comment]
Main branch is actually more up to date than dev branch  in this case, i removed the hook for delayed registry of network prefabs because it did not seem necessary.
(I accidentally pushed these changes to main instead of dev)

**Comment by Hamunii** [comment]
If I'm not mistaken, this also adds outside enemies to the inside enemies list? These enemy lists exist:
`testAllEnemiesLevel.Enemies`
`testAllEnemiesLevel.OutsideEnemies`
`testAllEnemiesLevel.DaytimeEnemies`

**Comment by EvaisaDev** [comment]
Okay you are right about the new NetworkPrefabs thingy being broken, i guess i never tested it..?

**Comment by EvaisaDev** [comment]
> If I'm not mistaken, this also adds outside enemies to the inside enemies list? These enemy lists exist: `testAllEnemiesLevel.Enemies` `testAllEnemiesLevel.OutsideEnemies` `testAllEnemiesLevel.DaytimeEnemies`

Yeah you are right, this currently adds every enemy to the inside list, does the dev menu use the other lists? I have never used the dev menu myself as LethalThings has a ~~superior~~ dev menu built in.

**Comment by Hamunii** [comment]
@EvaisaDev The dev menu does use the other lists, and the list an enemy is in is where it will get spawned. So if you add an outside enemy to the inside enemies list, it will get spawned inside.

**Comment by EvaisaDev** [comment]
> @EvaisaDev The dev menu does use the other lists, and the list an enemy is in is where it will get spawned. So if you add an outside enemy to the inside enemies list, it will get spawned inside.

Ah okay, so it works the same as my own dev menu. neat, in that case yeah that needs to be changed in this PR

**Comment by VisualError** [comment]
> > @EvaisaDev The dev menu does use the other lists, and the list an enemy is in is where it will get spawned. So if you add an outside enemy to the inside enemies list, it will get spawned inside.
> 
> Ah okay, so it works the same as my own dev menu. neat, in that case yeah that needs to be changed in this PR

I've added these changes now

**Comment by EvaisaDev** [comment]
Seems good!

**Pull request merged**
